#!/usr/bin/env bash
clang -std=gnu11 -O3 -g -Wall -Wno-microsoft-anon-tag -fms-extensions -no-pie -Wno-unused-function -fno-omit-frame-pointer $@ -o BQN src/opt/single.c -lm
# gcc -std=gnu11 -O3 -g -Wall -Wno-parentheses -Wno-misleading-indentation -Wno-unused-function -fms-extensions -no-pie -fno-omit-frame-pointer $@ -o BQN src/opt/single.c -lm
