#!/usr/bin/env bash
if [[ $# -ne 1 ]]; then
  echo "Usage: ./genRuntime path/to/mlochbaum/BQN"
  exit
fi
./cc.bqn $1 r0 > src/runtime0
./cc.bqn $1 r1 > src/runtime1
./cc.bqn $1 c > src/compiler
./cc.bqn $1 f > src/formatter
